### ISSUE TITLE
How do you include these into a project?

### ISSUE THREAD

**Issue by geuis** [heardrwt/RHAdditions#1]
I'm looking specifically at the NSWindow+RHPreventCaptureAdditions files. I'm inexperienced at Objective-c and I'm not sure how these are meant to be included in another project. I've tried including the .h in my app delegate and also adding them to the build phase, but the preventWindowFromBeingCaptured method doesn't show up on NSWindow objects.

**Comment by cottonmalone** [comment]
Hi Richard,
I am a python developer but I am trying to add NSWindow+RHPreventCaptureAdditions to [iTerm2](https://github.com/gnachman/iTerm2) for a project.
I have tried adding the code to NSWindow+iTerm.h but I have had no success in getting this to work. I normally would not bother a fellow developer but I could not find any docs online other than you repo on the subject.
Thanks in advance for the help,
Cotton
